# Generated by Django 4.2.11 on 2025-08-17 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('blocked', 'Blocked'), ('declined', 'Declined')], default='pending', help_text='Current status of the friendship', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('addressee', models.ForeignKey(help_text='User who received the friend request', on_delete=django.db.models.deletion.CASCADE, related_name='received_friend_requests', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(help_text='User who sent the friend request', on_delete=django.db.models.deletion.CASCADE, related_name='sent_friend_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Friendship',
                'verbose_name_plural': 'Friendships',
                'db_table': 'friendships_friendship',
                'indexes': [models.Index(fields=['requester', 'status'], name='friendships_request_5c1328_idx'), models.Index(fields=['addressee', 'status'], name='friendships_address_6e92a7_idx'), models.Index(fields=['status', 'created_at'], name='friendships_status_470a96_idx')],
                'unique_together': {('requester', 'addressee')},
            },
        ),
        migrations.CreateModel(
            name='ContactHash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_hash', models.CharField(db_index=True, help_text='HMAC-SHA256 hash of the phone number', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='User who uploaded this contact', on_delete=django.db.models.deletion.CASCADE, related_name='contact_hashes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact Hash',
                'verbose_name_plural': 'Contact Hashes',
                'db_table': 'friendships_contact_hash',
                'indexes': [models.Index(fields=['phone_hash'], name='friendships_phone_h_0e5100_idx'), models.Index(fields=['user', 'created_at'], name='friendships_user_id_c42306_idx')],
                'unique_together': {('user', 'phone_hash')},
            },
        ),
    ]
