# Generated by Django 4.2.11 on 2025-08-17 11:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_competitive', models.BooleanField(default=True, help_text='Whether this shared task has competitive scoring')),
                ('max_participants', models.PositiveIntegerField(default=10, help_text='Maximum number of participants allowed', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(50)])),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the shared task was created')),
                ('creator', models.ForeignKey(help_text='User who created this shared task', on_delete=django.db.models.deletion.CASCADE, related_name='created_shared_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shared Task',
                'verbose_name_plural': 'Shared Tasks',
                'db_table': 'task_management_shared_task',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='pending', help_text="Participant's completion status", max_length=10)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When this participant completed the task', null=True)),
                ('points_earned', models.PositiveIntegerField(default=0, help_text='Points earned by this participant')),
                ('joined_at', models.DateTimeField(auto_now_add=True, help_text='When the user joined this shared task')),
                ('shared_task', models.ForeignKey(help_text='The shared task', on_delete=django.db.models.deletion.CASCADE, to='task_management.sharedtask')),
                ('user', models.ForeignKey(help_text='The participating user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task Participation',
                'verbose_name_plural': 'Task Participations',
                'db_table': 'task_management_task_participation',
                'ordering': ['completed_at', '-points_earned'],
                'unique_together': {('shared_task', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Task title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed task description')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', help_text='Task priority level', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='pending', help_text='Current task status', max_length=10)),
                ('deadline', models.DateTimeField(blank=True, help_text='Task deadline (optional)', null=True)),
                ('points_value', models.PositiveIntegerField(default=10, help_text='Points awarded for completing this task', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('is_shared', models.BooleanField(default=False, help_text='Whether this task is shared with friends')),
                ('is_private', models.BooleanField(default=False, help_text='Whether this task is private (not visible in social feed)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the task was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the task was last updated')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the task was completed', null=True)),
                ('user', models.ForeignKey(help_text='The user who owns this task', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'db_table': 'task_management_task',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='sharedtask',
            name='participants',
            field=models.ManyToManyField(help_text='Users participating in this shared task', related_name='shared_tasks', through='task_management.TaskParticipation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sharedtask',
            name='task',
            field=models.OneToOneField(help_text='The base task that is shared', on_delete=django.db.models.deletion.CASCADE, related_name='shared_details', to='task_management.task'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', 'status'], name='task_manage_user_id_e188cd_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', 'priority'], name='task_manage_user_id_228819_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['deadline'], name='task_manage_deadlin_f09de5_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'deadline'], name='task_manage_status_be3aeb_idx'),
        ),
    ]
