# Generated by Django 4.2.11 on 2025-08-18 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_id', models.CharField(help_text='Unique identifier for the achievement', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Achievement name', max_length=100)),
                ('description', models.TextField(help_text='Achievement description')),
                ('icon', models.CharField(help_text='Icon identifier for the achievement', max_length=50)),
                ('category', models.CharField(choices=[('competitive', 'Competitive'), ('consistency', 'Consistency'), ('speed', 'Speed'), ('participation', 'Participation'), ('points', 'Points'), ('social', 'Social'), ('milestone', 'Milestone')], default='milestone', help_text='Achievement category', max_length=20)),
                ('points_reward', models.PositiveIntegerField(default=0, help_text='Points awarded when achievement is unlocked')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this achievement is currently active')),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', help_text='Achievement rarity level', max_length=20)),
                ('requirements_data', models.JSONField(default=dict, help_text='JSON data containing achievement requirements')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the achievement was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the achievement was last updated')),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
                'db_table': 'task_management_achievement',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True, help_text='When the achievement was unlocked')),
                ('points_awarded', models.PositiveIntegerField(default=0, help_text='Points awarded when this achievement was unlocked')),
                ('progress_data', models.JSONField(default=dict, help_text='JSON data for tracking achievement progress')),
                ('notification_sent', models.BooleanField(default=False, help_text='Whether notification was sent for this achievement')),
                ('is_featured', models.BooleanField(default=False, help_text='Whether this achievement should be featured in user profile')),
                ('achievement', models.ForeignKey(help_text='Achievement that was unlocked', on_delete=django.db.models.deletion.CASCADE, related_name='user_unlocks', to='task_management.achievement')),
                ('user', models.ForeignKey(help_text='User who unlocked the achievement', on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Achievement',
                'verbose_name_plural': 'User Achievements',
                'db_table': 'task_management_user_achievement',
                'ordering': ['-earned_at'],
            },
        ),
        migrations.CreateModel(
            name='AchievementProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_progress', models.PositiveIntegerField(default=0, help_text='Current progress value')),
                ('target_progress', models.PositiveIntegerField(default=1, help_text='Target progress value for completion')),
                ('progress_data', models.JSONField(default=dict, help_text='Additional progress tracking data')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='When progress was last updated')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When progress tracking started')),
                ('achievement', models.ForeignKey(help_text='Achievement being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='task_management.achievement')),
                ('user', models.ForeignKey(help_text='User whose progress is being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='achievement_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Achievement Progress',
                'verbose_name_plural': 'Achievement Progress',
                'db_table': 'task_management_achievement_progress',
                'ordering': ['-last_updated'],
            },
        ),
        migrations.AddIndex(
            model_name='achievement',
            index=models.Index(fields=['achievement_id'], name='task_manage_achieve_8b15ce_idx'),
        ),
        migrations.AddIndex(
            model_name='achievement',
            index=models.Index(fields=['category', 'is_active'], name='task_manage_categor_e92701_idx'),
        ),
        migrations.AddIndex(
            model_name='achievement',
            index=models.Index(fields=['rarity'], name='task_manage_rarity_f8e8bc_idx'),
        ),
        migrations.AddIndex(
            model_name='userachievement',
            index=models.Index(fields=['user', 'earned_at'], name='task_manage_user_id_998187_idx'),
        ),
        migrations.AddIndex(
            model_name='userachievement',
            index=models.Index(fields=['achievement', 'earned_at'], name='task_manage_achieve_2c66cf_idx'),
        ),
        migrations.AddIndex(
            model_name='userachievement',
            index=models.Index(fields=['is_featured'], name='task_manage_is_feat_2eadd7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userachievement',
            unique_together={('user', 'achievement')},
        ),
        migrations.AddIndex(
            model_name='achievementprogress',
            index=models.Index(fields=['user', 'last_updated'], name='task_manage_user_id_8c6d24_idx'),
        ),
        migrations.AddIndex(
            model_name='achievementprogress',
            index=models.Index(fields=['achievement'], name='task_manage_achieve_af4e87_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='achievementprogress',
            unique_together={('user', 'achievement')},
        ),
    ]
