# Generated by Django 4.2.11 on 2025-08-18 16:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import social_feed.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('task_completed', 'Task Completed'), ('achievement_earned', 'Achievement Earned'), ('shared_task_completed', 'Shared Task Completed'), ('milestone_reached', 'Milestone Reached'), ('shared_task_created', 'Shared Task Created'), ('friend_joined', 'Friend Joined'), ('streak_achieved', 'Streak Achieved'), ('leaderboard_position', 'Leaderboard Position'), ('photo_shared', 'Photo Shared'), ('celebration', 'Celebration'), ('workout_completed', 'Workout Completed'), ('goal_achieved', 'Goal Achieved')], help_text='Type of activity performed', max_length=30)),
                ('title', models.CharField(help_text='Activity title for display', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the activity')),
                ('content', models.JSONField(default=dict, help_text='Flexible content storage for activity-specific data')),
                ('is_public', models.BooleanField(default=True, help_text='Whether this activity is visible to friends')),
                ('points_earned', models.IntegerField(default=0, help_text='Points earned from this activity', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the activity was created')),
                ('related_task_id', models.IntegerField(blank=True, help_text='ID of related task if applicable', null=True)),
                ('related_shared_task_id', models.IntegerField(blank=True, help_text='ID of related shared task if applicable', null=True)),
                ('related_achievement_id', models.IntegerField(blank=True, help_text='ID of related achievement if applicable', null=True)),
                ('user', models.ForeignKey(help_text='User who performed the activity', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Feed Entry',
                'verbose_name_plural': 'Activity Feed Entries',
                'db_table': 'social_feed_activity_feed',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialFeedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('photo', 'Photo Post'), ('achievement', 'Achievement Post'), ('celebration', 'Celebration Post'), ('milestone', 'Milestone Post'), ('workout', 'Workout Post'), ('goal', 'Goal Post'), ('text', 'Text Post')], default='text', help_text='Type of social post', max_length=20)),
                ('title', models.CharField(blank=True, help_text='Post title', max_length=200)),
                ('content', models.TextField(blank=True, help_text='Post content/description', max_length=1000)),
                ('location_name', models.CharField(blank=True, help_text="Location name (e.g., 'Central Park, NYC')", max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, help_text='Post location latitude', max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, help_text='Post location longitude', max_digits=11, null=True)),
                ('is_public', models.BooleanField(default=True, help_text='Whether post is visible to all friends')),
                ('friends_only', models.BooleanField(default=True, help_text='Whether post is visible only to friends')),
                ('likes_count', models.PositiveIntegerField(default=0, help_text='Number of likes')),
                ('comments_count', models.PositiveIntegerField(default=0, help_text='Number of comments')),
                ('shares_count', models.PositiveIntegerField(default=0, help_text='Number of shares')),
                ('related_task_id', models.IntegerField(blank=True, help_text='Related task ID if applicable', null=True)),
                ('related_achievement_id', models.IntegerField(blank=True, help_text='Related achievement ID if applicable', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who created the post', on_delete=django.db.models.deletion.CASCADE, related_name='social_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Social Feed Post',
                'verbose_name_plural': 'Social Feed Posts',
                'db_table': 'social_feed_social_post',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NearbyFriendRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.DecimalField(decimal_places=2, help_text='Distance between users in kilometers', max_digits=8)),
                ('recommendation_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Recommendation score based on various factors', max_digits=5)),
                ('is_dismissed', models.BooleanField(default=False, help_text='Whether user has dismissed this recommendation')),
                ('is_contacted', models.BooleanField(default=False, help_text='Whether user has sent friend request to recommended user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recommended_user', models.ForeignKey(help_text='User being recommended', on_delete=django.db.models.deletion.CASCADE, related_name='recommended_to', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User receiving the recommendation', on_delete=django.db.models.deletion.CASCADE, related_name='nearby_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nearby Friend Recommendation',
                'verbose_name_plural': 'Nearby Friend Recommendations',
                'db_table': 'social_feed_nearby_friend_recommendation',
                'ordering': ['-recommendation_score', 'distance_km'],
            },
        ),
        migrations.CreateModel(
            name='ActivityPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Photo image file', upload_to=social_feed.models.activity_photo_upload_path)),
                ('caption', models.CharField(blank=True, help_text='Photo caption', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order for multiple photos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(help_text='Activity this photo belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='social_feed.activityfeed')),
            ],
            options={
                'verbose_name': 'Activity Photo',
                'verbose_name_plural': 'Activity Photos',
                'db_table': 'social_feed_activity_photo',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('cheer', 'Cheer'), ('celebrate', 'Celebrate'), ('fire', 'Fire')], help_text='Type of interaction', max_length=20)),
                ('comment_text', models.TextField(blank=True, help_text='Comment text (for comment interactions)', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the interaction was created')),
                ('activity', models.ForeignKey(help_text='Activity being interacted with', on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='social_feed.activityfeed')),
                ('user', models.ForeignKey(help_text='User performing the interaction', on_delete=django.db.models.deletion.CASCADE, related_name='activity_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Interaction',
                'verbose_name_plural': 'Activity Interactions',
                'db_table': 'social_feed_activity_interaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityFeedSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_task_completions', models.BooleanField(default=True, help_text='Show when user completes tasks')),
                ('show_achievements', models.BooleanField(default=True, help_text='Show when user earns achievements')),
                ('show_milestones', models.BooleanField(default=True, help_text='Show when user reaches point milestones')),
                ('show_shared_task_activities', models.BooleanField(default=True, help_text='Show shared task related activities')),
                ('show_leaderboard_positions', models.BooleanField(default=True, help_text='Show when user achieves high leaderboard positions')),
                ('friends_only', models.BooleanField(default=True, help_text='Only show activities to friends')),
                ('notify_on_interactions', models.BooleanField(default=True, help_text='Send notifications when friends interact with activities')),
                ('notify_on_friend_activities', models.BooleanField(default=True, help_text='Send notifications for friend activities')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='User these settings belong to', on_delete=django.db.models.deletion.CASCADE, related_name='activity_feed_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Feed Settings',
                'verbose_name_plural': 'Activity Feed Settings',
                'db_table': 'social_feed_activity_feed_settings',
            },
        ),
        migrations.CreateModel(
            name='ActivityFeedCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(help_text='Cache key identifier', max_length=100)),
                ('cache_data', models.JSONField(help_text='Cached activity feed data')),
                ('expires_at', models.DateTimeField(help_text='When this cache entry expires')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='User this cache belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='activity_feed_cache', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Feed Cache',
                'verbose_name_plural': 'Activity Feed Cache',
                'db_table': 'social_feed_activity_feed_cache',
            },
        ),
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, help_text="User's latitude coordinate", max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, help_text="User's longitude coordinate", max_digits=11, null=True)),
                ('city', models.CharField(blank=True, help_text="User's city", max_length=100)),
                ('country', models.CharField(blank=True, help_text="User's country", max_length=100)),
                ('is_location_enabled', models.BooleanField(default=False, help_text='Whether user has enabled location sharing')),
                ('location_precision', models.CharField(choices=[('exact', 'Exact Location'), ('city', 'City Level'), ('country', 'Country Level'), ('disabled', 'Disabled')], default='city', help_text='Level of location precision to share', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='When location was last updated')),
                ('user', models.OneToOneField(help_text='User this location belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='location', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Location',
                'verbose_name_plural': 'User Locations',
                'db_table': 'social_feed_user_location',
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='social_feed_latitud_0fc429_idx'), models.Index(fields=['city', 'country'], name='social_feed_city_21b0b4_idx'), models.Index(fields=['is_location_enabled'], name='social_feed_is_loca_0676b9_idx')],
            },
        ),
        migrations.CreateModel(
            name='SocialPostPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Photo image file', upload_to=social_feed.models.social_post_photo_upload_path)),
                ('caption', models.CharField(blank=True, help_text='Photo caption', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order for multiple photos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(help_text='Post this photo belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='social_feed.socialfeedpost')),
            ],
            options={
                'verbose_name': 'Social Post Photo',
                'verbose_name_plural': 'Social Post Photos',
                'db_table': 'social_feed_social_post_photo',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['post', 'order'], name='social_feed_post_id_f24b68_idx')],
            },
        ),
        migrations.CreateModel(
            name='SocialPostInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('like', 'Like'), ('love', 'Love'), ('laugh', 'Laugh'), ('wow', 'Wow'), ('sad', 'Sad'), ('angry', 'Angry'), ('fire', 'Fire'), ('celebrate', 'Celebrate'), ('comment', 'Comment'), ('share', 'Share')], help_text='Type of interaction', max_length=20)),
                ('comment_text', models.TextField(blank=True, help_text='Comment text (for comment interactions)', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(help_text='Post being interacted with', on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='social_feed.socialfeedpost')),
                ('user', models.ForeignKey(help_text='User performing the interaction', on_delete=django.db.models.deletion.CASCADE, related_name='social_post_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Social Post Interaction',
                'verbose_name_plural': 'Social Post Interactions',
                'db_table': 'social_feed_social_post_interaction',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['post', 'interaction_type'], name='social_feed_post_id_a14ebb_idx'), models.Index(fields=['user', 'created_at'], name='social_feed_user_id_56c934_idx')],
                'unique_together': {('post', 'user', 'interaction_type')},
            },
        ),
        migrations.AddIndex(
            model_name='socialfeedpost',
            index=models.Index(fields=['user', 'created_at'], name='social_feed_user_id_dd212c_idx'),
        ),
        migrations.AddIndex(
            model_name='socialfeedpost',
            index=models.Index(fields=['post_type', 'created_at'], name='social_feed_post_ty_8250f0_idx'),
        ),
        migrations.AddIndex(
            model_name='socialfeedpost',
            index=models.Index(fields=['is_public', 'created_at'], name='social_feed_is_publ_903cd4_idx'),
        ),
        migrations.AddIndex(
            model_name='socialfeedpost',
            index=models.Index(fields=['latitude', 'longitude'], name='social_feed_latitud_7b51e2_idx'),
        ),
        migrations.AddIndex(
            model_name='nearbyfriendrecommendation',
            index=models.Index(fields=['user', 'is_dismissed'], name='social_feed_user_id_a059bf_idx'),
        ),
        migrations.AddIndex(
            model_name='nearbyfriendrecommendation',
            index=models.Index(fields=['recommendation_score'], name='social_feed_recomme_e4de6e_idx'),
        ),
        migrations.AddIndex(
            model_name='nearbyfriendrecommendation',
            index=models.Index(fields=['created_at'], name='social_feed_created_339066_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='nearbyfriendrecommendation',
            unique_together={('user', 'recommended_user')},
        ),
        migrations.AddIndex(
            model_name='activityphoto',
            index=models.Index(fields=['activity', 'order'], name='social_feed_activit_1e2af7_idx'),
        ),
        migrations.AddIndex(
            model_name='activityinteraction',
            index=models.Index(fields=['activity', 'interaction_type'], name='social_feed_activit_532044_idx'),
        ),
        migrations.AddIndex(
            model_name='activityinteraction',
            index=models.Index(fields=['user', 'created_at'], name='social_feed_user_id_f827c6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='activityinteraction',
            unique_together={('activity', 'user', 'interaction_type')},
        ),
        migrations.AddIndex(
            model_name='activityfeedcache',
            index=models.Index(fields=['user', 'cache_key'], name='social_feed_user_id_c2707a_idx'),
        ),
        migrations.AddIndex(
            model_name='activityfeedcache',
            index=models.Index(fields=['expires_at'], name='social_feed_expires_802ad1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='activityfeedcache',
            unique_together={('user', 'cache_key')},
        ),
        migrations.AddIndex(
            model_name='activityfeed',
            index=models.Index(fields=['user', 'created_at'], name='social_feed_user_id_aa9c16_idx'),
        ),
        migrations.AddIndex(
            model_name='activityfeed',
            index=models.Index(fields=['activity_type', 'created_at'], name='social_feed_activit_e8d111_idx'),
        ),
        migrations.AddIndex(
            model_name='activityfeed',
            index=models.Index(fields=['is_public', 'created_at'], name='social_feed_is_publ_42e0dc_idx'),
        ),
        migrations.AddIndex(
            model_name='activityfeed',
            index=models.Index(fields=['created_at'], name='social_feed_created_46fc0e_idx'),
        ),
    ]
