# Generated by Django 4.2.11 on 2025-08-18 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_feed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityFeedStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_type', models.CharField(choices=[('photo', 'Photo Story'), ('video', 'Video Story'), ('text', 'Text Story'), ('achievement', 'Achievement Story'), ('workout', 'Workout Story')], default='photo', help_text='Type of story', max_length=20)),
                ('content', models.TextField(blank=True, help_text='Story text content', max_length=500)),
                ('media_file', models.FileField(blank=True, help_text='Photo or video file for story', null=True, upload_to='stories/')),
                ('background_color', models.CharField(default='#000000', help_text='Background color for text stories (hex code)', max_length=7)),
                ('location_name', models.CharField(blank=True, help_text='Location name for story', max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, help_text='Story location latitude', max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, help_text='Story location longitude', max_digits=11, null=True)),
                ('views_count', models.PositiveIntegerField(default=0, help_text='Number of views')),
                ('related_task_id', models.IntegerField(blank=True, help_text='Related task ID if applicable', null=True)),
                ('related_achievement_id', models.IntegerField(blank=True, help_text='Related achievement ID if applicable', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='When the story expires (24 hours from creation)')),
                ('user', models.ForeignKey(help_text='User who created the story', on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Feed Story',
                'verbose_name_plural': 'Activity Feed Stories',
                'db_table': 'social_feed_activity_feed_story',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserEngagementMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_activities_created', models.PositiveIntegerField(default=0, help_text='Total activities created by user')),
                ('total_posts_created', models.PositiveIntegerField(default=0, help_text='Total social posts created by user')),
                ('total_stories_created', models.PositiveIntegerField(default=0, help_text='Total stories created by user')),
                ('total_likes_given', models.PositiveIntegerField(default=0, help_text='Total likes given by user')),
                ('total_likes_received', models.PositiveIntegerField(default=0, help_text='Total likes received by user')),
                ('total_comments_given', models.PositiveIntegerField(default=0, help_text='Total comments given by user')),
                ('total_comments_received', models.PositiveIntegerField(default=0, help_text='Total comments received by user')),
                ('activity_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Overall activity engagement score', max_digits=8)),
                ('social_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Social interaction engagement score', max_digits=8)),
                ('last_activity_date', models.DateTimeField(blank=True, help_text='Date of last activity', null=True)),
                ('current_streak_days', models.PositiveIntegerField(default=0, help_text='Current daily activity streak')),
                ('longest_streak_days', models.PositiveIntegerField(default=0, help_text='Longest daily activity streak')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='User these metrics belong to', on_delete=django.db.models.deletion.CASCADE, related_name='engagement_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Engagement Metrics',
                'verbose_name_plural': 'User Engagement Metrics',
                'db_table': 'social_feed_user_engagement_metrics',
            },
        ),
        migrations.CreateModel(
            name='SocialChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Challenge title', max_length=200)),
                ('description', models.TextField(help_text='Challenge description', max_length=1000)),
                ('challenge_type', models.CharField(choices=[('step_count', 'Step Count Challenge'), ('workout_streak', 'Workout Streak Challenge'), ('task_completion', 'Task Completion Challenge'), ('points_race', 'Points Race Challenge'), ('custom', 'Custom Challenge')], help_text='Type of challenge', max_length=20)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', help_text='Challenge status', max_length=20)),
                ('target_value', models.PositiveIntegerField(help_text='Target value for the challenge (steps, points, etc.)')),
                ('duration_days', models.PositiveIntegerField(default=7, help_text='Challenge duration in days')),
                ('max_participants', models.PositiveIntegerField(default=20, help_text='Maximum number of participants')),
                ('start_date', models.DateTimeField(help_text='When the challenge starts')),
                ('end_date', models.DateTimeField(help_text='When the challenge ends')),
                ('winner_points', models.PositiveIntegerField(default=100, help_text='Points awarded to winner')),
                ('participation_points', models.PositiveIntegerField(default=25, help_text='Points awarded for participation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(help_text='User who created the challenge', on_delete=django.db.models.deletion.CASCADE, related_name='created_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Social Challenge',
                'verbose_name_plural': 'Social Challenges',
                'db_table': 'social_feed_social_challenge',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('dropped_out', 'Dropped Out')], default='active', help_text='Participation status', max_length=20)),
                ('current_progress', models.PositiveIntegerField(default=0, help_text='Current progress towards target')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When user completed the challenge', null=True)),
                ('points_earned', models.PositiveIntegerField(default=0, help_text='Points earned from this challenge')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(help_text='Challenge being participated in', on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='social_feed.socialchallenge')),
                ('user', models.ForeignKey(help_text='Participating user', on_delete=django.db.models.deletion.CASCADE, related_name='challenge_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Challenge Participation',
                'verbose_name_plural': 'Challenge Participations',
                'db_table': 'social_feed_challenge_participation',
                'ordering': ['-current_progress', 'joined_at'],
            },
        ),
        migrations.CreateModel(
            name='StoryView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(help_text='Story that was viewed', on_delete=django.db.models.deletion.CASCADE, related_name='story_views', to='social_feed.activityfeedstory')),
                ('viewer', models.ForeignKey(help_text='User who viewed the story', on_delete=django.db.models.deletion.CASCADE, related_name='story_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Story View',
                'verbose_name_plural': 'Story Views',
                'db_table': 'social_feed_story_view',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['story', 'viewed_at'], name='social_feed_story_i_fc6de2_idx'), models.Index(fields=['viewer', 'viewed_at'], name='social_feed_viewer__ef9d00_idx')],
                'unique_together': {('story', 'viewer')},
            },
        ),
        migrations.AddIndex(
            model_name='socialchallenge',
            index=models.Index(fields=['status', 'start_date'], name='social_feed_status_6a2e77_idx'),
        ),
        migrations.AddIndex(
            model_name='socialchallenge',
            index=models.Index(fields=['challenge_type', 'status'], name='social_feed_challen_3c5d7c_idx'),
        ),
        migrations.AddIndex(
            model_name='socialchallenge',
            index=models.Index(fields=['creator', 'status'], name='social_feed_creator_5f2edb_idx'),
        ),
        migrations.AddIndex(
            model_name='challengeparticipation',
            index=models.Index(fields=['challenge', 'status'], name='social_feed_challen_bc8f35_idx'),
        ),
        migrations.AddIndex(
            model_name='challengeparticipation',
            index=models.Index(fields=['user', 'status'], name='social_feed_user_id_e40d61_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='challengeparticipation',
            unique_together={('challenge', 'user')},
        ),
        migrations.AddIndex(
            model_name='activityfeedstory',
            index=models.Index(fields=['user', 'expires_at'], name='social_feed_user_id_54fed4_idx'),
        ),
        migrations.AddIndex(
            model_name='activityfeedstory',
            index=models.Index(fields=['expires_at'], name='social_feed_expires_fdf3ea_idx'),
        ),
        migrations.AddIndex(
            model_name='activityfeedstory',
            index=models.Index(fields=['created_at'], name='social_feed_created_fe85d1_idx'),
        ),
    ]
