# Generated by Django 4.2.7 on 2025-08-18 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0002_achievement_userachievement_achievementprogress_and_more'),
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completely_private', models.BooleanField(default=True, help_text='Whether task is completely hidden from all friends')),
                ('hide_from_activity_feed', models.BooleanField(default=True, help_text='Whether to hide task completion from activity feed')),
                ('hide_from_leaderboards', models.BooleanField(default=True, help_text='Whether to exclude points from leaderboards')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.OneToOneField(help_text='Task that has private settings', on_delete=django.db.models.deletion.CASCADE, related_name='private_settings', to='task_management.task')),
                ('visible_to_friends', models.ManyToManyField(blank=True, help_text='Specific friends who can see this private task', related_name='visible_private_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Private Task',
                'verbose_name_plural': 'Private Tasks',
                'db_table': 'user_accounts_private_task',
            },
        ),
        migrations.CreateModel(
            name='PrivacySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_visibility', models.CharField(choices=[('public', 'Public'), ('friends', 'Friends Only'), ('private', 'Private')], default='friends', help_text="Who can view user's profile", max_length=20)),
                ('task_visibility', models.CharField(choices=[('public', 'Public'), ('friends', 'Friends Only'), ('private', 'Private')], default='friends', help_text="Who can see user's tasks", max_length=20)),
                ('task_completion_visibility', models.CharField(choices=[('public', 'Public'), ('friends', 'Friends Only'), ('private', 'Private')], default='friends', help_text='Who can see when user completes tasks', max_length=20)),
                ('achievement_visibility', models.CharField(choices=[('public', 'Public'), ('friends', 'Friends Only'), ('private', 'Private')], default='friends', help_text="Who can see user's achievements", max_length=20)),
                ('activity_feed_visibility', models.CharField(choices=[('all', 'All Activities'), ('achievements_only', 'Achievements Only'), ('tasks_only', 'Tasks Only'), ('none', 'None')], default='all', help_text='What activities to show in feed', max_length=20)),
                ('show_in_leaderboards', models.BooleanField(default=True, help_text='Whether to appear in friend leaderboards')),
                ('allow_friend_requests', models.BooleanField(default=True, help_text='Whether to accept friend requests')),
                ('allow_shared_task_invites', models.BooleanField(default=True, help_text='Whether to receive shared task invitations')),
                ('share_location', models.BooleanField(default=False, help_text='Whether to share location for nearby friend suggestions')),
                ('allow_contact_sync', models.BooleanField(default=True, help_text='Whether to allow contact syncing for friend discovery')),
                ('show_online_status', models.BooleanField(default=True, help_text='Whether to show online/offline status to friends')),
                ('show_last_seen', models.BooleanField(default=True, help_text='Whether to show last seen timestamp to friends')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='User these privacy settings belong to', on_delete=django.db.models.deletion.CASCADE, related_name='privacy_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Privacy Settings',
                'verbose_name_plural': 'Privacy Settings',
                'db_table': 'user_accounts_privacy_settings',
            },
        ),
        migrations.CreateModel(
            name='FriendPrivacySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility_level', models.CharField(choices=[('full', 'Full Access'), ('limited', 'Limited Access'), ('minimal', 'Minimal Access'), ('blocked', 'Blocked')], default='full', help_text='Level of access this friend has', max_length=20)),
                ('can_see_tasks', models.BooleanField(default=True, help_text="Whether friend can see user's tasks")),
                ('can_see_task_completions', models.BooleanField(default=True, help_text='Whether friend can see task completions')),
                ('can_see_achievements', models.BooleanField(default=True, help_text='Whether friend can see achievements')),
                ('can_invite_to_shared_tasks', models.BooleanField(default=True, help_text='Whether friend can invite user to shared tasks')),
                ('can_see_activity_feed', models.BooleanField(default=True, help_text="Whether friend can see user's activity feed")),
                ('can_see_leaderboard_position', models.BooleanField(default=True, help_text='Whether friend can see user in leaderboards')),
                ('notify_on_activities', models.BooleanField(default=True, help_text="Whether to notify this friend of user's activities")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('friend', models.ForeignKey(help_text='Friend these settings apply to', on_delete=django.db.models.deletion.CASCADE, related_name='privacy_settings_for_me', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User who owns these privacy settings', on_delete=django.db.models.deletion.CASCADE, related_name='friend_privacy_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Friend Privacy Settings',
                'verbose_name_plural': 'Friend Privacy Settings',
                'db_table': 'user_accounts_friend_privacy_settings',
                'indexes': [models.Index(fields=['user', 'visibility_level'], name='user_accoun_user_id_4b7b30_idx'), models.Index(fields=['friend'], name='user_accoun_friend__717056_idx')],
                'unique_together': {('user', 'friend')},
            },
        ),
    ]
